package:
  name: ptd_esr
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.1") }}

source:
  path: .

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  script:
    - $PYTHON setup.py install
  entry_points:
    - start_ptd = cli.cli_data:main

requirements:
  build:
    - python==3.10
    - setuptools
  run:
    - python==3.10
    - pandas
    - requests
    - pyyaml
    - airflow==2.4.3